[versions]
agp = "8.13.2"
kotlin = "2.2.21"
compose-bom = "2026.06.01"
core = "1.17.0"
appcompat = "1.7.1"
activity = "1.12.2"
lifecycle = "2.10.0"
navigation = "2.9.8"
datastore = "1.2.1"
coroutines = "1.10.2"
media3 = "1.10.1"
annotation = "1.9.1"
oboe = "1.9.3"

[libraries]
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
media3-common = { module = "androidx.media3:media3-common", version.ref = "media3" }
media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
oboe = { module = "com.google.oboe:oboe", version.ref = "oboe" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
